name: "Nix build"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: "Basic CLI and web build"
      run: |
        nix build .#tclip .#tclipd
    - name: "Docker image build (dry run)"
      run: |
        nix develop --command -- mkctr --gopaths="./cmd/tclipd:/bin/tclipd" --tags="latest" --base="gcr.io/distroless/static" --repos=ghcr.io/tailscale-dev/tclip --ldflags="-w -s" -- /bin/tclipd
    - name: "docker login"
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      if: "github.event_name == 'push' && github.ref_name == 'main'"
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: "Docker image push"
      if: "github.event_name == 'push' && github.ref_name == 'main'"
      run: |
        nix develop --command -- mkctr --gopaths="./cmd/tclipd:/bin/tclipd" --tags="latest" --base="gcr.io/distroless/static" --repos=ghcr.io/tailscale-dev/tclip --push --ldflags="-w -s" -- /bin/tclipd
    - name: "Portable service build"
      run: |
        nix build .#portable-service
        mkdir -p var
        cp ./result/*.raw ./var
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: portable-service
        path: ./var/*.raw
